spring.application.name=corazon-gourmet

# ==========================================================================
# CONFIGURACI\u00d3N DE LA BASE DE DATOS MYSQL (H\u00cdBRIDO: LOCAL / NUBE)
# ==========================================================================
# Si la variable DB_URL no existe, usar\u00e1 por defecto tu localhost local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bd_corazon_gourmet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false}
# Si la variable DB_USER no existe, usar\u00e1 por defecto root
spring.datasource.username=${DB_USER:root}
# Si la variable DB_PASSWORD no existe, usar\u00e1 por defecto root
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================================================
# CONFIGURACI\u00d3N DE JPA / HIBERNATE  
# ==========================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================================================
# CONFIGURACI\u00d3N DE SEGURIDAD - TOKENS JWT
# ==========================================================================
# Clave firma robusta (M\u00ednimo 32 caracteres para evitar errores de firma con jjwt)
jwt.secret=ClaveSecretaDePruebaParaCorazonGourmet2026SistemasUTP
# Tiempo de expiraci\u00f3n del token (86400000 ms = 24 horas activas)
jwt.expiration=86400000

# ==========================================================================
# CONFIGURACI\u00d3N DE PROYECTO Y PUERTOS
# ==========================================================================
# Puerto predeterminado para tu API REST en Spring Boot
server.port=8080

# URL del Frontend en Angular para la gesti\u00f3n de CORS (Soporta local y nube en simult\u00e1neo)
app.frontend.url=http://localhost:4200,https://corazon-gourmet-frontend.vercel.app

# ==========================================================================
# REPORTE DE LOGS DETALLADOS (DEBUGGING)
# ==========================================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE