spring.application.name=corazon-gourmet

# ==========================================================================
# CONFIGURACI\u00d3N DE LA BASE DE DATOS MYSQL (H\u00cdBRIDO: LOCAL / NUBE)
# ==========================================================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bd_corazon_gourmet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================================================
# CONFIGURACI\u00d3N DE JPA / HIBERNATE  
# ==========================================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================================================
# CONFIGURACI\u00d3N DE SEGURIDAD - TOKENS JWT
# ==========================================================================
jwt.secret=ClaveSecretaDePruebaParaCorazonGourmet2026SistemasUTP
jwt.expiration=86400000

# ==========================================================================
# CONFIGURACI\u00d3N DE PROYECTO Y PUERTOS (IMPORTANTE PARA RENDER)
# ==========================================================================
# Permitimos que Render inyecte su puerto din\u00e1mico obligatoriamente
server.port=${PORT:8080}

# Leemos la variable de entorno que pusimos en Render, o localhost por defecto
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}

# ==========================================================================
# REPORTE DE LOGS DETALLADOS (DEBUGGING)
# ==========================================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Configura la zona horaria del servidor al tiempo de Lima
spring.jackson.time-zone=America/Lima